/*
 * @Desc:
 * @Date: 2020-01-27 15:42:23
 * @LastEditors: Please set LastEditors
 * @LastEditTime: 2020-10-08 11:15
 */
export const tablecolumns_config = [
  {
    title: "",
    width: 60,
    dataIndex: "expandedbtn",
    key: "expandedbtn",
    align: "center",
    fixed: 'left',
    scopedSlots:{customRender:"expandedbtn"},
  },
  {
    title: "序号",
    width: 70,
    dataIndex: "_index",
    key: "_index",
    align: "left",
    fixed: 'left',
  },
  {
    title: "日期",
    width: 150,
    dataIndex: "financeDate",
    key: "financeDate",
    align: "center",
    fixed: 'left',
  },
  {
    title: "商户名称",
    width: 230,
    dataIndex: "merchantName",
    key: "merchantName",
    align: "left",
    scopedSlots: { customRender: "merchantName" },
  },
  {
    title: "商户类型",
    dataIndex: "agentLevel",
    key: "agentLevel",
    // width: 130,
    align: "left",
    scopedSlots: { customRender: "agentLevel" },
  },
  {
    title: "结算币种",
    dataIndex: "currencyStr",
    key: "currencyStr",
    width: 150,
    align: "center",
    scopedSlots: { customRender: "currencyStr" },
  },
  {
    title: "投注用户数",
    dataIndex: "orderUserNum",
    key: "orderUserNum",
    width: 130,
    align: "right",
    scopedSlots: { customRender: "orderUserNum" },
  },
  {
    title: "投注笔数",
    dataIndex: "orderValidNum",
    key: "orderValidNum",
    width: 150,
    align: "right",    
    scopedSlots: { customRender: "orderValidNum" },
  },
  {
    title: "投注金额",
    dataIndex: "orderAmountTotal",
    key: "orderAmountTotal",
    width: 150,
    align: "right",
    scopedSlots: { customRender: "orderAmountTotal" },
  },
  {
    title: "平台盈利",
    dataIndex: "platformProfit",
    key: "platformProfit",
    width: 150,
    align: "right",
    scopedSlots: { customRender: "platformProfit" },
  },
  {
    title: "盈利率",
    dataIndex: "platformProfitRate",
    key: "platformProfitRate",
    width: 130,
    align: "right",
    scopedSlots: { customRender: "platformProfitRate" },
  },
  {
    title: "下载对账单",
    key: "action",
    width: 140,
    scopedSlots: { customRender: "action" },
    align: "center",
    fixed: 'right',
  }
];
export const total_config = [
  {
    title: "",
    width: 60,
    dataIndex: "expandedbtn",
    key: "expandedbtn",
    align: "center",
    // fixed: 'left',
    scopedSlots:{customRender:"expandedbtn"},
  },
  {
    title: "序号",
    width: 70,
    dataIndex: "_index",
    key: "_index",
    align: "left",
    // fixed: 'left',
  },
  {
    title: "日期",
    width: 150,
    dataIndex: "financeDate",
    key: "financeDate",
    align: "center",
    // fixed: 'left',
  },
  {
    title: "商户名称",
    width: 180,
    dataIndex: "merchantName",
    key: "merchantName",
    align: "left",
    scopedSlots: { customRender: "merchantName" },
  },
  {
    title: "商户类型",
    dataIndex: "agentLevel",
    key: "agentLevel",
    // width: 130,
    align: "left",
    scopedSlots: { customRender: "agentLevel" },
  },
  {
    title: "结算币种",
    dataIndex: "currencyStr",
    key: "currencyStr",
    width: 150,
    align: "center",
    scopedSlots: { customRender: "currencyStr" },
  },
  {
    title: "投注用户数",
    dataIndex: "orderUserNum",
    key: "orderUserNum",
    width: 130,
    align: "right",
    scopedSlots: { customRender: "orderUserNum" },
  },
  {
    title: "投注笔数",
    dataIndex: "orderValidNum",
    key: "orderValidNum",
    width: 150,
    align: "right",    
    scopedSlots: { customRender: "orderValidNum" },
  },
  {
    title: "投注金额",
    dataIndex: "orderAmountTotal",
    key: "orderAmountTotal",
    width: 150,
    align: "right",
    scopedSlots: { customRender: "orderAmountTotal" },
  },
  {
    title: "平台盈利",
    dataIndex: "platformProfit",
    key: "platformProfit",
    width: 150,
    align: "right",
    scopedSlots: { customRender: "platformProfit" },
  },
  {
    title: "盈利率",
    dataIndex: "platformProfitRate",
    key: "platformProfitRate",
    width: 130,
    align: "right",
    scopedSlots: { customRender: "platformProfitRate" },
  },
  {
    title: "下载对账单",
    key: "action",
    width: 140,
    scopedSlots: { customRender: "action" },
    align: "center",
    // fixed: 'right',
  }
];
