export const tablecolumns_config = [
  {
    name: "id",
    label: "序号",
    align: "center",
    field: "id",
    fixed: 1,
    width: 101,
    min: 101
  },

  {
    name: "shanghubianhao",
    label: "商户编号",
    align: "center",
    classes: "panda-table-col-text-indent",
    field: "shanghubianhao",
    fixed: 1,
    width: 109,
    min: 109,
    sortable: true,
  },
  {
    name: "shanghumingcheng",
    label: "商户名称",
    align: "center",
    classes: "panda-table-col-text-indent",
    field: "shanghumingcheng",
    fixed: 1,
    width: 142,
    min: 142,
    sortable: true,
  },
  {
    name: "shanghudengji",
    label: "商户等级",
    align: "center",
    classes: "panda-table-col-text-indent",
    field: "shanghudengji",
    fixed: 1,
    width: 154,
    min: 154,
    sortable: true,
  },
  {
    name: "Email",
    label: "Email",
    align: "center",
    field: "Email",
    classes: "panda-table-col-text-indent",
    fixed: 1,
    width: 210,
    min: 210,
    sortable: true,
  },
  {
    name: "shangwulianxiren",
    label: "商务联系人",
    align: "center",
    classes: "panda-table-col-text-indent",
    field: "shangwulianxiren",
    fixed: 1,
    width: 104,
    min: 104,
    sortable: true,
  },
  {
    name: "lianxidianhua",
    label: "联系电话",
    align: "center",
    classes: "panda-table-col-text-indent",
    field: "lianxidianhua",
    fixed: 1,
    width: 133,
    min: 133,
    sortable: true,
  },

  {
    name: "shanghuguanliyuan",
    label: "商户管理员",
    align: "center",
    classes: "panda-table-col-text-indent",
    field: "shanghuguanliyuan",
    fixed: 1,
    width: 202,
    min: 202,
    sortable: true,
  },
  {
    name: "ruzhushijian",
    label: "入驻时间",
    align: "center",
    classes: "panda-table-col-text-indent",
    field: "ruzhushijian",
    fixed: 1,
    width: 184,
    min: 184,
    sortable: true,
  },
  {
    name: "shanghuzhuangtai",
    label: "商户状态",
    align: "center",
    classes: "panda-table-col-text-indent",
    field: "shanghuzhuangtai",
    fixed: 1,
    width: 184,
    min: 184,
    sortable: true,
  },
  {
    name: "caozuo",
    label: "操作",
    align: "center",
    classes: "panda-table-col-text-indent",
    field: "caozuo",
    fixed: 1,
    width: 184,
    min: 184,
    sortable: true,
  },
 
];
